# This file contains all available configuration options
# with their default values.

# options for analysis running
run:
  concurrency: 4
  tests: true
  skip-dirs:
    - vendor
  skip-files:
  timeout: 5m

#  modules-download-mode: vendor


linters-settings:
  gocyclo:
    min-complexity: 20

linters:
  # enable-all: true
  # disable:
  #   - lll
  #   - funlen
  #   - unused
  #   - godox
  #   - gocognit
  #   - gochecknoinits
  #   - prealloc
  #   - gochecknoglobals
  #   - wsl

  disable-all: true
  enable:
    - deadcode
    - dupl
    - errcheck
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - golint
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - varcheck
    - whitespace
    - gas
    - gosec
    - scopelint
    - interfacer
    - nakedret

#    - bodyclose
#    - depguard
#    - dogsled
#    - unused
#    - maligned




